



#let to = math.arrow


// BEGIN AUTO-GENERATED CATEGORY MACROS
// This block is generated by script/generate_category_macros.py.
// Do not edit manually; edit script/macro_table.json and regenerate.

// custom_macros
#let kk = math.bold("k")
#let kkk = math.bb("k")
#let rkk = math.kappa
#let fkk = math.scr("K")
#let im = math.sqrt("-1")
#let ten = math.times.o
#let tensor = math.times.o
#let injmap = math.arrow.r.hook
#let surjmap = math.arrow.r.twohead
#let ratmap = math.arrow.r.dashed
#let colim = math.op("colim")
#let acts = math.arrow.r.curve
#let isom = math.tilde.equiv

// categories
#let Set = math.bold("Set")
#let Var = math.bold("Var")
#let Sch = math.bold("Sch")
#let sch = math.bold("sch")
#let Av = math.bold("Av")
#let Alg = math.bold("Alg")
#let Ring = math.bold("Ring")
#let Mod = math.bold("Mod")
#let module = math.bold("mod")
#let TopMod = math.bold("TopMod")
#let Banmod = math.bold("Banmod")
#let Vect = math.bold("Vect")
#let vect = math.bold("vect")
#let Grp = math.bold("Grp")
#let Grpd = math.bold("Grpd")
#let Ab = math.bold("Ab")
#let Top = math.bold("Top")
#let Open = math.bold("Open")
#let Shv = math.bold("Shv")
#let PShv = math.bold("PShv")
#let QCoh = math.bold("QCoh")
#let Coh = math.bold("Coh")
#let Cat = math.bold("Cat")
#let AlgSp = math.bold("AlgSp")
#let AlgGrp = math.bold("AlgGrp")

// up_operators
#let real = math.op("Re")
#let image = math.op("Im")
#let id = math.op("id")
#let vol = math.op("vol")
#let length = math.op("length")
#let Length = math.op("Length")
#let disc = math.op("disc")
#let gr = math.op("gr")
#let pr = math.op("pr")
#let Frob = math.op("Frob")
#let Gal = math.op("Gal")
#let Nm = math.op("Nm")
#let Spec = math.op("Spec")
#let mSpec = math.op("mSpec")
#let Proj = math.op("Proj")
#let CH = math.op("CH")
#let Obj = math.op("Obj")
#let Fun = math.op("Fun")
#let Mor = math.op("Mor")
#let res = math.op("res")
#let Res = math.op("Res")
#let Ext = math.op("Ext")
#let Tor = math.op("Tor")
#let Hom = math.op("Hom")
#let Eq = math.op("Eq")
#let cohdim = math.op("coh.dim")
#let hldim = math.op("hl.dim")
#let projdim = math.op("proj.dim")
#let injdim = math.op("inj.dim")
#let depth = math.op("depth")
#let idealht = math.op("idealht")
#let codim = math.op("codim")
#let Supp = math.op("Supp")
#let trdeg = math.op("trdeg")
#let Ass = math.op("Ass")
#let Ann = math.op("Ann")
#let Der = math.op("Der")
#let Frac = math.op("Frac")
#let Mult = math.op("Mult")
#let nilp = math.op("nil")
#let characteristic = math.op("char")
#let Pic = math.op("Pic")
#let NS = math.op("NS")
#let Exc = math.op("Exc")
#let Sing = math.op("Sing")
#let Bl = math.op("Bl")
#let Reg = math.op("Reg")
#let Psef = math.op("Psef")
#let Nef = math.op("Nef")
#let Eff = math.op("Eff")
#let Mov = math.op("Mov")
#let Amp = math.op("Amp")
#let Bigcone = math.op("Big")
#let Bs = math.op("Bs")
#let Stab = math.op("Stab")
#let Cone = math.op("Cone")
#let Div = math.op("Div")
#let WDiv = math.op("WDiv")
#let CaDiv = math.op("CaDiv")
#let divisor = math.op("div")
#let Cl = math.op("Cl")
#let CaCl = math.op("CaCl")
#let WCl = math.op("WCl")
#let Bir = math.op("Bir")
#let GL = math.op("GL")
#let SO = math.op("SO")
#let PGL = math.op("PGL")
#let SL = math.op("SL")
#let Spin = math.op("Spin")
#let PSL = math.op("PSL")
#let Sp = math.op("Sp")
#let SU = math.op("SU")
#let Gr = math.op("Gr")
#let ad = math.op("ad")
#let Ad = math.op("Ad")
#let Lie = math.op("Lie")
#let diag = math.op("diag")
#let Ker = math.op("Ker")
#let Coker = math.op("Coker")
#let coker = math.op("coker")
#let ord = math.op("ord")
#let rank = math.op("rank")
#let tr = math.op("tr")
#let Tr = math.op("Tr")
#let Aut = math.op("Aut")
#let End = math.op("End")
#let Sym = math.op("Sym")
#let Qnil = math.op("Qnil")
#let Red = math.op("Red")
#let Int = math.op("Int")

// frak_operators
#let Hilb = math.frak("Hilb")
#let Grass = math.frak("Grass")

// cal_operators
#let calHom = math.cal("calHom")
#let calMor = math.cal("calMor")

// END AUTO-GENERATED CATEGORY MACROS

